manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: pmalecka
      url-base: https://github.com/pmalecka
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: pim447
      remote: pmalecka
      revision: new-zmk     # the trackball driver branch you chose
      path: modules/pim447  # lives under modules/ so Zephyr picks it up
  self:
    path: config
